### ISSUE TITLE
Profile page - first tab

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/helppr#1]
- [x] Show user info in the fields and all addresses associated with this user
- [x] If the user changes some info and click in "Salvar" a request is done to update the info
- [x] A list of addresses is shown under the "Endereco" title. If the user click on the pencil after the address the fields are populated for the user to edit his address. And the button "Adicionar endereco" is hidden and another 2 buttons are shown. The first button is to save the address change, the second should delete the address after a confirmation modal. 
- [x] When the user first comes to the page, the address fields are blank, if the user fills the fields then the "Adicionar endereco" button is enabled and if the user clicks it makes a request to add the address.

**Comment by donrus** [comment]
- there is an oportunity to add several phone numbers and emails in admin panel, but on the profile page there is only one. So now in profile is shown only the first phone number and email
