### ISSUE TITLE
Booking page changes

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/helppr#10]
- [x] Saved address dropdown should be visible only if the user is logged in
- [x] Implement search address once the zip is added to fill up the other fields
- [x] Once the user click in agendar, if he's logged out, redirect to the registration page and fill up the fields that were already entered by the user (address, zip, city, etc)
- [x] The times dropdown needs to be calculated depending on the total hours that the client needs to hire. For example, if the user is hiring 3hours, the times on the list should be (7 to 10, 8 to 11, 9 to 12 ) and so on.
- [x] Also carry the value of square meters to the registration page
- [x] Once the user enter the square meters, select on the dropdowns the number of profissionals and hours suggested
 - [x] If some zip is entered but it doesn't belong to the supported cities the address shouldn't be saved.
-  [x] After the user log out, if he comes back to the book page, the dropdown to select the addresses list is showing and it shouldn't. I believe on logout some cookie isn't cleared properly.
 - [x] If the user is logged in and instead of selecting one address from the previously save addresses decided to add another address, this should be added to his list of addresses.
- [x] If somebody select Avulso, we need to pass the corresponding day of the week value so the api works, for example if somebody select 25 of december we need to pass Wednesday as selected.

**Comment by donrus** [comment]
"If some zip is entered but it doesn't belong to the supported cities the address shouldn't be saved"
It should be appropriate error from backend API http://helppr-staging.herokuapp.com/api/v1/address_details
