### ISSUE TITLE
Iron calculation

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/helppr#11]
On the second and third tabs because there's the service of ironing, some different calculations should be done. Instead of entering the square meters, the number of pieces to iron should be entered. The corresponding selected value should be converted in hours and send to the api. For example on the 3rd tab 4, 6 and 8 hours respectively.

**Comment by donrus** [comment]
I don't understand formula. For example: user enters 8 items (or 3 items) to iron, how much hours it should be?

**Comment by lpissinali** [comment]
The number of hours to add is on the <option> value of the dropdown.
