### ISSUE TITLE
Booking page

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/helppr#5]
- [x] On the first part of the form the user can check the price for a service without being logged in. After the user enters the square meters, the professionals and the duration it should return the price, the suggested duration and suggested professionals.
- [x] After the user click on continue booking, if the user is logged in show a dropdwon with the list of addresses, otherwise show the fields to fill up the user address.
- [x] Depending on the user selection for Periodicidade (frequency) show or hide the days of the week below. When Avulso is selected, hide the days of the week.
 - [x] Once the fields are filled send a post to http://helppr-staging.herokuapp.com/api/v1/order_services and show confirmation message.
- [x] Change order price value from comma to dot.

**Comment by donrus** [comment]
- user can't edit address, because in REST parameters should be address id.
- which parameter of REST affected by periodically-select?
- how set time of order (in select only two values)?
- what mean next parameters in REST: "type_of_hiring", "sales_channel", "item_optional"?

**Comment by lpissinali** [comment]
I'm adding more times on dropdown, I'll check the other issues later.

**Comment by donrus** [comment]
For each tab on book page I need values (true or false) of these options:
- interior_of_windows
- refrigerator
- external_area 
- closet_interior
- clothes_ironing
- windows_outside
- oven

**Comment by lpissinali** [comment]
Tab 1

- interior_of_windows - true only on tab 4
- refrigerator - true only on tab 4
- external_area - false on all
- closet_interior - true only on tab 4
- clothes_ironing - true on tabs 2 and 3
- windows_outside - false on all tabs
- oven - false on all tabs
