### ISSUE TITLE
Payment page

### ISSUE THREAD

**Issue by lpissinali** [lpissinali/helppr#7]
Once the booking is confirmed, on the payment page we need to display the details of the order and the total value. If the user has a cc on file it should the cc image with number and expiration date, otherwise show a form to fill up the cc details. After send the payment request.

**Comment by donrus** [comment]
- for payment. User press button on the site, the window of payment system opens, user enter card data in fields from payment window. We receive token from payment system and send this token in rest parameters 
![image](https://user-images.githubusercontent.com/32517764/70905986-5e332180-2016-11ea-916d-98ffe6624da3.png)
So you on the payment page card foto is not needed and even if user enter its card's data we can do nothing with them.
